wine/routes.py
"""Create web views for EOS Wine Log"""

from itertools import count
import sys

from flask import (Blueprint,
                   Flask,
                   redirect,
                   render_template,
                   request,
                   session as login_session,
                   url_for)
from flask_login import login_required
from sqlalchemy import (asc,
                        cast,
                        desc,
                        func,
                        null,
                        Numeric, nullslast,
                        update)

from models import (Base,
                    Country,
                    open_db_session,
                    Region,
                    Sommelier,
                    Wine)


wine_bp = Blueprint(
    'wine_bp', __name__,
    static_folder='static',
    static_url_path='/wine/static',
    template_folder='templates'
    )


# Display Wine App home page, showing all the wines in the db
@wine_bp.route('/wine')
def wineHome():
    """Display Wine App home page"""
    DBSession = open_db_session()
    # QUERY so that result is a list with element 0 a Wine object
    # and the other three elements are the relations to it.
    # Note that sommelier_id could be None (NULL in DB) so 
    # we need an outer join to keep the Wine object in that case
    wines = DBSession.query(Wine, Country.name, Region.name, Sommelier.username).join(
                        Country, Wine.country_id==Country.id).join(
                        Region, Wine.region_id==Region.id).outerjoin(
                        Sommelier, Wine.sommelier_id==Sommelier.id).order_by(
                        desc(Wine.rating)).all()
    DBSession.close()
    # Replace new line (\r\n) characters in description with <br>
    for wine in wines:
        s = (wine[0].description)
        if s: # filter out null values
            s = s.replace("\r\n", "<br>")
            wine[0].description = s
    return render_template('home.html', wines=wines)


# Display a table of all wines
@wine_bp.route('/wine/table')
def wineTable():
    """Display wine table"""
    DBSession = open_db_session()
    # QUERY so that result is a list with element 0 a Wine object
    # and the other two elements are the relations to it.
    wines = DBSession.query(Wine, Country.name, Region.name).join(
                        Country, Wine.country_id==Country.id).join(
                        Region, Wine.region_id==Region.id).order_by(
                        desc(Wine.id)).all()
    DBSession.close()
    # Pass number of wines to the template for display
    numWines = len(wines)
    return render_template('table.html', wines=wines, numWines=numWines)


@wine_bp.route('/wine/stats')
def wineStats():
    """Show statistics on the wines in the database"""
    DBSession = open_db_session()
    total_num_wines = DBSession.query(
                        Wine.id).count()
    #### QUERY FOR STATS BY COUNTRY ####
    # Country Table creates object with four columns:
    # name, number of wines, average rating, average price, average abv
    # Note rating and abv are type "real" which has to be cast 
    # as Numeric for the round function to work
    # IN SQL:
    # SELECT 
    #     country.name, 
    #     COUNT(wine.country_id),
	#     ROUND(AVG(wine.rating),2) AS rating, 
	#     ROUND(AVG(wine.price::NUMERIC), 2) AS price, 
	#     ROUND(AVG(wine.ABV::NUMERIC), 2) as abv 
	# FROM wine 
    # JOIN country ON wine.country_id=country.id 
    # GROUP BY country.name 
    # ORDER BY name DESC; 
    wines_by_country = DBSession.query(
                        Country.name, func.count(Wine.country_id),\
                            func.round(func.avg(Wine.rating), 1),\
                            func.round(cast(
                                func.avg(Wine.price), Numeric), 2),\
                            func.round(cast(
                                func.avg(Wine.abv), Numeric), 1)).\
                        join(Wine, Wine.country_id==Country.id).\
                        group_by(Country.name).\
                        order_by(desc(func.count(Wine.country_id)),\
                            Country.name).\
                        all()
    wines_by_region = DBSession.query(
                        Region.name, func.count(Wine.region_id),\
                            func.round(func.avg(Wine.rating), 1),\
                            func.round(cast(
                                func.avg(Wine.price), Numeric), 2),\
                            func.round(cast(
                                func.avg(Wine.abv), Numeric), 1)).\
                        join(Wine, Wine.region_id==Region.id).\
                        group_by(Region.name).\
                        order_by(desc(func.count(Wine.region_id)),\
                            Region.name).\
                        all()
    wines_by_appellation = DBSession.query(
                        Wine.appellation, func.count(Wine.appellation),\
                            func.round(func.avg(Wine.rating), 1),\
                            func.round(cast(
                                func.avg(Wine.price), Numeric), 2),\
                            func.round(cast(
                                func.avg(Wine.abv), Numeric), 1)).\
                        group_by(Wine.appellation).\
                        order_by(desc(func.count(Wine.appellation)),\
                            Wine.appellation).\
                        all()
    wines_by_category = DBSession.query(
                        Wine.categories, func.count(Wine.categories)).\
                        group_by(Wine.categories).\
                        order_by(desc(func.count(Wine.categories)),\
                            Wine.categories).\
                        all()
    wines_by_rating = DBSession.query(
                        Wine.rating, func.count(Wine.rating)).\
                        group_by(Wine.rating).\
                        order_by(desc(Wine.rating)).\
                        all()
    wines_by_abv = DBSession.query(
                        Wine.abv, func.count(Wine.abv)).\
                        group_by(Wine.abv).\
                        order_by(Wine.abv).\
                        all()
    wines_by_year = DBSession.query(
                        Wine.year, func.count(Wine.year)).\
                        group_by(Wine.year).\
                        order_by(Wine.year).\
                        all()
    wines_by_varietals = DBSession.query(
                        Wine.varietals, func.count(Wine.varietals),\
                            func.round(func.avg(Wine.rating), 1),\
                            func.round(cast(
                                func.avg(Wine.price), Numeric), 2),\
                            func.round(cast(
                                func.avg(Wine.abv), Numeric), 1)).\
                        group_by(Wine.varietals).\
                        order_by(desc(func.count(Wine.varietals)),\
                            Wine.varietals).\
                        all()
    # NULL values are not counted by func.count, so "None" appears
    # in tables with count = 0. To fix this,
    # create a dictionary to pass null counts for each column
    # to the page; insert into tables using JavaScript
    null_counts = {}
    null_counts['abv'] = total_num_wines - DBSession.query(
                            func.count(Wine.abv)).scalar()
    null_counts['appellation'] = total_num_wines - DBSession.query(
                            func.count(Wine.appellation)).scalar()
    null_counts['year'] = total_num_wines - DBSession.query(
                            func.count(Wine.year)).scalar()
    DBSession.close()
    return render_template('stats.html',\
        total_num_wines=total_num_wines,\
        wines_by_country=wines_by_country,\
        wines_by_region=wines_by_region,\
        wines_by_appellation=wines_by_appellation,\
        wines_by_category=wines_by_category,\
        wines_by_rating=wines_by_rating,\
        wines_by_abv=wines_by_abv,\
        wines_by_year=wines_by_year,\
        wines_by_varietals=wines_by_varietals,\
        null_counts=null_counts)    
    
# Display a single wine for editing
@wine_bp.route('/wine/wineEdit')
@login_required
def wineEdit():
    """Display a single wine for editing"""
    # Display wine for editing
    DBSession = open_db_session()
    # QUERY one wine by id (id is passed in query string)
    # Result is a Wine object
    wineid = request.args.get("wineid")
    wineToEdit = DBSession.query(Wine).\
        filter(Wine.id == wineid).\
        one_or_none()
    DBSession.close()
    # can't iterate through single wine in template
    # so copying attributes (vars) into a dictionary
    wineDict = {}
    wineDict = (vars(wineToEdit))
    # remove var that isn't part of data
    wineDict.pop('_sa_instance_state')
    # treat description separately to display on top of page
    wineDescription = wineDict.pop('description')
    # Make some tweaks to the data
    for w in wineDict.copy():
    # display any None (null) values as blank spaces
    # then it is easy to convert them to NULL again
    # on their way back to the database
    # (see newwine view)
        if wineDict[w] == None:
            wineDict[w] = ""
    # remove ids (wine id, country_id, region_id, sommelier_id)
    # use a copy as a dict cannot be changed during iteration
        if w.find('id') != -1:
            wineDict.pop(w)
    # Sort by key (requires building new dictionary)
    sorted_dict = {}
    sorted_keys = sorted(wineDict)
    for k in sorted_keys:
        sorted_dict[k]=wineDict[k]
    return render_template('wineEdit.html', wineid=wineid,
        wineToEdit=sorted_dict, wineDescription=wineDescription)


# Update wine record with values from wineEdit form view
@wine_bp.route('/wine/wineUpdate', methods=['POST'])
@login_required
def wineUpdate():
    """Update a wine record"""
    # Convert blank strings in form to None (NULL)

wine/templates/countriesRegions.html
{% extends "wineBase.html" %}

{% block content %}

<script>
    // For renaming regions: Display regions in dropdown associated 
    // with the country selected by user
    function populateRegion(x) {
        let selectedCountryID = document.getElementById('rr_country_id').value;
        let eid = document.getElementById('rr_region_id');
        eid.innerHTML = "<option value=''>--select--</option>"
        {% for region in regions %}
            if ({{region.country_id}} == selectedCountryID) { 
                eid.innerHTML += "<option value={{region.id}}>{{region.name}}</option>"
            }
        {% endfor %}
    }
    function populateRegionToDelete(x) {
        // Display regions in dropdown associated with the country 
        // selected by user. Only show regions that have no wines
        // associated with them
        let selectedCountryID = document.getElementById('country_id').value;
        let eid = document.getElementById('region_id');
        eid.innerHTML = "<option value=''>--select--</option>"
        {% for region in deletableRegions %}
            if ({{region.country_id}} == selectedCountryID) { 
                eid.innerHTML += "<option value={{region.id}}>{{region.name}}</option>"
            }
        {% endfor %}
    }
</script>

<header id=mainHeader>
	<h1>Manage Countries and Regions</h1>
</header>

<section id=manageCountriesRegions>

<h2>Existing Countries and Regions</h2>
<table>
    <tr>
        <th>Country</th>
        <th>Region</th>
    </tr>
    {% for country in countries %}
        <tr>
            <td>{{country.name}}</td>
            <td>
            {% for region in regions %}
                {% if country.id == region.country_id %}
                    {{region.name}} <br>
                {% endif %}
            {% endfor %}
            </td>
        </tr>
    {% endfor %}
</table>

<h2>Create a New Country</h2>
    <form action="/wine/countryNew" method = "post">
        <label for="name">Name:</label>
        <input type ="text" maxlength="100" name="name" required>
        <button type="submit" id="submit">Create Country</button>
    </form>

<h2>Create a New Region</h2>
    <form action="/wine/regionNew" method = "post">
        <p>
            <label for="country_id">Country:</label>
                <select name="country_id">
                {% for country in countries %}
                    <option value={{country.id}}>{{country.name}}</option>
                {% endfor %}
                </select>
            <label for="name">Name:</label>
            <input type="text" maxlength="100" name="name" required>
            <button type="submit" id="submit">Create Region</button>
        </p>    
    </form>

<h2>Rename a Country</h2>
    <form action="/wine/countryRename" method="post">
        <label for="country_id">Current Name:</label>
            <select name="country_id">
                {% for country in countries %}
                    <option value={{country.id}}>{{country.name}}</option>
                {% endfor %}
            </select>
        <br><label for="newname">New Name:</label>
            <input type ="text" maxlength="100" name="newname" required>
        <button type="submit" id="submit">Rename Country</button>
    </form>

<h2>Rename a Region</h2>
    <form action="/wine/regionRename" method = "post">
        <p>
            <label for="country_id">Country:</label>
                <select name="country_id" id="rr_country_id" 
                    onchange="populateRegion()">
                    <option value="none">--select--</option>
                    {% for country in countries %}
                    <option value={{country.id}}>{{country.name}}</option>
                {% endfor %}
                </select>
            <label for="region_id">Region:</label>
                <select name="region_id" id="rr_region_id">
                    <option value="none">--select country first--</option>
                </select>
            <br><label for="newname">New Name:</label>
                <input type ="text" maxlength="100" name="newname" required>
            <button type="submit" id="submit">Rename Region</button>
        </p>    
    </form>

<h2>Delete a Country</h2>
    <p style="font-style: italic">
        Only countries without associated regions or wines
         can be deleted. None may appear in the dropdown.</p>
    <form action="/wine/countryDelete" method="post">
        <label for="country_id">Name:</label>
            <select name="country_id">
                {% for country in deletableCountries %}
                    <option value={{country.id}}>{{country.name}}</option>
                {% endfor %}
            </select>
            <button type="submit" id="submit">Delete Country</button>
    </form>

<h2>Delete a Region</h2>
    <p style="font-style: italic">Only regions without associated 
        wines can be deleted. None may appear in the dropdown.</p>
    <form action="/wine/regionDelete" method = "post">
        <p>
            <label for="country_id">Country:</label>
                <select name="country_id" id="country_id" 
                    onchange="populateRegionToDelete()">
                    <option value="none">--select--</option>
                    {% for country in countries %}
                    <option value={{country.id}}>{{country.name}}</option>
                    {% endfor %}
                </select>
            <label for="region_id">Region:</label>
                <select name="region_id" id="region_id">
                    <option value="none">--select country first--</option>
                </select>
            <button type="submit" id="submit">Delete Region</button>
        </p>    
    </form>

</section>

{% endblock %}

wine/templates/home.html
{% extends "wineBase.html" %}

{% block content %}

<script>
    // Display All Wines
    function showWines() {
        var htmlstring = "";
        // wine is a list: [wineobject, countryname, regionname, som.username]
        {% for wine in wines %}
            // put id in div so item can be displayed directly
            htmlstring += "<div class=wineItem id='{{ wine[0].id }}'>" + 
                "<div class=wineLabel>";
                    {% if wine[0].label_photo %}
                        var photo_url = "{{url_for('labels_bp.static', filename=wine[0].label_photo)}}";
                        htmlstring += "<img src=" + photo_url + ">";
                    {% endif %}
                htmlstring += "</div>" +
                "<div class=wineInfo>" +
                    // Display Name and Description
		    "<div class=wineName>" +
		   	 "<p>{{ wine[0].name }}</p>" +
		    "</div>";
                    // replace escapes for lt & gt with actual chars
                    // so <br> is treated as a tag not part of the string
                    var s = "{{wine[0].description}}";
                    var t = s.replace(/&lt;/g, "<");
                    var u = t.replace(/&gt;/g, ">");
                    htmlstring += "<p>" + u + "</p>";
                    // Display Title Information
                    htmlstring += "<div class='wineInfoTitle'>" +
                        "{{wine[0].year}} - " +
                        "{{wine[1]}} - " + // country name
                        "{{wine[2]}}"; // region name
                        var a = "{{wine[0].appellation}}";
                        if (a != "None") { // don't show blank appellations
                            htmlstring += " - " + a; 
                        }
                    htmlstring += "</div>";
                    // Display Second Line of Information
                    // Colorize rating
                    var rating = "{{wine[0].rating}}";
                    var ratingColor = getRatingColor(rating);
                    htmlstring += "<div class='wineInfoLine'>" +
                        "<span class='wineInfoRating'" +
                            "style=background-color:" + ratingColor + ">" +
                            rating + "</span> points ";
                    // Add price with two digits after decimal
                    htmlstring += "$" + parseFloat("{{wine[0].price}}").toFixed(2);
                    // Add abv (has one digit after decimal by default)
                    htmlstring += " {{wine[0].abv}} abv</div>";
                    // Display Third Line of Information
                    htmlstring += "<div class='wineInfoLine'>";
                        // Avoid blank date_tested values breaking display
                        {% if wine[0].date_tasted %}
                            htmlstring += "First tasted on {{wine[0].date_tasted.strftime('%Y-%m-%d')}}. ";
                        {% else %}
                            htmlstring += "No first taste date. ";
                        {% endif %}
                        htmlstring += "Times Tasted: {{wine[0].times_tasted}}" +
                    "</div>";
                    // Display Fourth Line of Information
                    htmlstring += "<div class='wineInfoLine'>";
                        // Avoid blank date_tested values breaking display
                        htmlstring += "{{ wine[0].categories }} wine made from {{ wine[0].varietals }}." +
                    "</div>";
                    // Display Fifth Line of Information
                    htmlstring += "<div class='wineInfoLine'>" +    
                        "Purchased at {{wine[0].purchased_at}}  ";
                        // OMIT: " Entered by {{wine[3]}}. "; 
                        //     (sommelier name)
                        // Add button to go to top of page
                        htmlstring += " <a href='#top' class='button button_top'>top&uarr;</a>";
                        // Include Edit Button if user is logged in
                        // Wine ID will be passed in a query string
                        {% if current_user.is_authenticated %} 
                            var url_string = "{{url_for('wine_bp.wineEdit', wineid=wine[0].id)}}";
                            htmlstring += " <a href=" + url_string + " class='button button_edit'>Edit</a>";
                        {% endif %}
                    htmlstring += "</div>" +
                "</div>" +
            "</div>";
        {% endfor %}
        winelist.innerHTML = htmlstring;
    }
    // Return color for rating background
    function getRatingColor(rating) {    
    if (rating >= 95) {
        return "fuchsia";
    } else if (rating >= 90) {
        return "springgreen";
    } else if (rating >= 85) {
        return "aqua";
    } else if (rating >= 80) {
        return "silver";
    } else {
        //return "#FFFF70"; //same as page background, i.e. clear   
    }
}

</script>

<header id=mainHeader><h1>Wines</h1></header>

<!-- CONTROL SECTION CURRENTLY HIDDEN -->
<section id=controlWrap class=defaultWrap style="display: none">
    <div id=controlBar class=defaultBar>Control the View</div>
    <div id=controlBox class=defaultBox>
        <p>
        <em>Eventually you'll be able to sort the wines here</em>
        </p>
    </div>
</section>

<div id="winelist">
    <script>showWines();</script>
</div>

{% endblock %}

wine/templates/stats.html
{% extends "wineBase.html" %}

{% block content %}

<header id=mainHeader>
    <h1>Wine Log Statistics [ {{ total_num_wines }} Wines ]</h1>
</header>

<div class="statsBox">
    <h2>By Country</h2>
    <table class="tablesort">
        <tr>
            <th>Country</th>
            <th>Total</th>
            <th>Avg Rating</th>
            <th>Avg Price</th>
            <th>Avg ABV</th>
        </tr>
        {% for row in wines_by_country %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
            <td>{{row[2]}}</td>
            <td>{{row[3]}}</td>
            <td>{{row[4]}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="statsBox">
    <h2>By Region</h2>
    <table class="tablesort">
        <tr>
            <th>Region</th>
            <th>Total</th>
            <th>Avg Rating</th>
            <th>Avg Price</th>
            <th>Avg ABV</th>
        </tr>
        {% for row in wines_by_region %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
            <td>{{row[2]}}</td>
            <td>{{row[3]}}</td>
            <td>{{row[4]}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="statsBox">
    <h2>By Appellation</h2>
    <table class="tablesort" id="appellation">
        <tr>
            <th>Appellation</th>
            <th>Total</th>
            <th>Avg Rating</th>
            <th>Avg Price</th>
            <th>Avg ABV</th>
        </tr>
        {% for row in wines_by_appellation %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
            <td>{{row[2]}}</td>
            <td>{{row[3]}}</td>
            <td>{{row[4]}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="statsBox">
    <h2>By Varietals</h2>
    <table class="tablesort">
        <tr>
            <th>Varietals</th>
            <th>Total</th>
            <th>Avg Rating</th>
            <th>Avg Price</th>
            <th>Avg ABV</th>
        </tr>
        {% for row in wines_by_varietals %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
            <td>{{row[2]}}</td>
            <td>{{row[3]}}</td>
            <td>{{row[4]}}</td>
         </tr>
        {% endfor %}
    </table>
</div>
<div class="statsBox">
    <h2>By Category</h2>
    <table class="tablesort">
        <tr>
            <th>Category</th>
            <th>Total</th>
        </tr>
        {% for row in wines_by_category %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="statsBox">
    <h2>By Rating</h2>
    <table class="tablesort">
        <tr>
            <th>Rating</th>
            <th>Total</th>
        </tr>
        {% for row in wines_by_rating %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="statsBox">
    <h2>By ABV</h2>
    <table class="tablesort" id="abv">
        <tr>
            <th>ABV</th>
            <th>Total</th>
        </tr>
        {% for row in wines_by_abv %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="statsBox">
    <h2>By Year</h2>
    <table class="tablesort" id="year">
        <tr>
            <th>Year</th>
            <th>Total</th>
        </tr>
        {% for row in wines_by_year %}
        <tr>
            <td>{{row[0]}}</td>
            <td>{{row[1]}}</td>
        </tr>
        {% endfor %}
    </table>
</div>

<script>
    // Correct "0" counts of "None" values
    {% for i in null_counts %}
        for (row of document.getElementById('{{i}}').rows) {
            if (row.cells[0].innerText === "None") {
                row.cells[1].innerText = {{null_counts[i]}};
            };
        };
    {% endfor %}
    // Enable sorting by clicking on table headers
    activate_table_sorting();
    // Scan table for prices with ".0" instead of ".00" and fix
    t = document.querySelector('table');
    let counter = 0;
    let priceColNum = 0;
    for (cell of t.rows[0].cells) {
        if (cell.innerText === "Price") {
            priceColNum = counter;
            break;
        }
        counter++;
    }
    for (row of t.rows){
        if (row.cells[priceColNum].innerText.match(/.0$/)){
            row.cells[priceColNum].innerText += "0";
        }
    }

</script>

{% endblock %}

wine/templates/table.html
{% extends "wineBase.html" %}

{% block content %}

<header id=mainHeader>
    <h1>All Wines in the Database [ {{ numWines }} ]</h1>
</header>

<div class=posLeftOfVP>
    <table class="tablesort">
        <tr>
            <th>ID</th>
            <th>Country</th>
            <th>Region</th>
            <th>Appellation</th>
            <th>Name</th>
            <th>Year</th>
            <th>Price</th>
            <th>ABV</th>
            <th>Rating</th>
            <th>Tasted</th>
            <th>Categories</th>
            <th>Varietals</th>
            <th>Action</th>
        </tr>
        {% for wine in wines %}
        <tr>
            <td>{{wine[0].id}}</td>
            <td>{{wine[1]}}</td>
            <td>{{wine[2]}}</td>
            <td>{{wine[0].appellation}}</td>
            <td>
                <a href="{{ url_for('wine_bp.wineHome', _anchor=wine[0].id) }}">
                    {{wine[0].name}}
                </a>
            </td>
            <td>{{wine[0].year}}</td>
            <td>{{wine[0].price}}</td>
            <td>{{wine[0].abv}}</td>
            <td>{{wine[0].rating}}</td>
            <td>{{wine[0].date_tasted}}</td>
            <td>{{wine[0].categories}}</td>
            <td>{{wine[0].varietals}}</td>
            <td>
                {% if current_user.is_authenticated %}
                <a href="{{url_for('wine_bp.wineEdit', wineid=wine[0].id)}}" class="button button_edit">Edit </a>
                <a href="{{url_for('wine_bp.wineDelete', wineid=wine[0].id)}}" class="button button_delete">Delete</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

</div>

<script>
    // Move the footer so it is a child of the div around the table
    // Otherwise the footer will render on top of the table
    // because the table is absolute positioned
    window.addEventListener('DOMContentLoaded', () => {
        const pf = document.getElementById('pageFooter');
        const tableWrapper = document.querySelector('.posLeftOfVP');
        tableWrapper.appendChild(pf);
    });
    // Enable sorting by clicking on table headers
    activate_table_sorting();
    // Scan table for prices with ".0" instead of ".00" and fix
    t = document.querySelector('table');
    let counter = 0;
    let priceColNum = 0;
    for (cell of t.rows[0].cells) {
        if (cell.innerText === "Price") {
            priceColNum = counter;
            break;
        }
        counter++;
    }
    for (row of t.rows){
        if (row.cells[priceColNum].innerText.match(/.0$/)){
            row.cells[priceColNum].innerText += "0";
        }
    }
</script>

{% endblock %}

wine/templates/wineBase.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description" content="EOS Wine Log">
    <meta name="keywords" content="wine">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Exult O Shores</title>
    <link rel="stylesheet" 
        href="{{ url_for('static', filename='styles_all.css') }}">
    <link rel="stylesheet" 
        href="{{ url_for('static', filename='styles_eos.css') }}">
	<link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Spectral|Libre+Baskerville|Open+Sans">
    <script src="{{ url_for('static', filename='scripts_all.js') }}"></script>
</head>

<body>
    <div id="bodyWrap">
        <header id="siteTitle">EOS Wine Log</header>
        <nav>
            <ul>
                <li>
                    <a href="/">EOS</a>
                </li>
                <li>
                    <a href="/wine">Home</a>
                </li>
                <li>
                    <a href="/wine/table">Table</a>
                </li>
                <li>
                    <a href="/wine/stats">Stats</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li>
                        <a href="/wine/wineNew">New</a>
                    </li>
                    <li>
                        <a href="/wine/countriesRegions">MCR</a>
                    </li>
                    <li>
                        Welcome {{ current_user.username }}!
                    </li>
                    <li>
                        <a href="/wine/logout">Log Out</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="/wine/login">Log In</a>
                    </li>
                {% endif %}
            </ul>
        </nav>

        <section id=notifications>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </section>
        
        <main>
            
            {% block content %}
            {% endblock %}
            
        </main>

        <footer id=pageFooter>
            <script>showPageFooter()</script>
        </footer>
    </div>

</body>

</html>